name: firstapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  animated_text_kit: ^2.0.1
  modal_progress_hud: ^0.1.3

  # Firebase
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  firebase_analytics: ^5.0.11
  google_sign_in: ^4.5.1
  cloud_firestore: ^0.13.3

  collection_ext: ^0.2.0
  provider: ^4.0.2
  tuple: ^1.0.3
  intl: ^0.16.1
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter:

  uses-material-design: true

  assets:
    - images/logo.png
    - images/google.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
#  fonts:
#    - family: app-icons
#      fonts:
#        - asset: fonts/app-icons.ttf
